
[package]
name = "bench"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
