
[package]
name = "types"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
