
[package]
name = "configd"
version = "0.2.3"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
crypto = { path = "../crypto" }
