
name: CI
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --workspace --features bls
      - name: Clippy
        run: cargo clippy --workspace --all-targets --features bls -- -D warnings
      - name: Tests
        run: cargo test --workspace --features bls -- --nocapture
